SPEED_MULTIPLIER = 1
STARTING_ROBOT_NUMBER = 2
MAX_ROBOT_NUMBER = 30
ROBOT_MONEY_COST = 3
ROBOT_FOO_COST = 6
FOOBAR_SELLING_PRICE = 1
MIN_FOOBAR_TO_SELL = 1
MAX_FOOBAR_TO_SELL = 5
BUILD_FOOBAR_CHANCE = 0.6

CHANGE_JOB_TIME = 5
MINE_FOO_TIME = 1
MINE_BAR_MIN_TIME = 0.5
MINE_BAR_MAX_TIME = 2
BUILD_FOOBAR_TIME = 2
SELL_FOOBAR_TIME = 10
